name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: khizkj
          outputs: |
            ./output/snake.svg
